### PR TITLE
Add v2.14 release to compatibility matrix

### PR DESCRIPTION
**Pull request by mattmcneeney**

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

Should we update the release process to remind people to do this as part of the normal release workflow?

**Comment by mattmcneeney** [comment]
We could, but it needs to be done _after_ the release is cut so the correct date can be added.

**Comment by zrob** [comment]
lgtm

**Comment by duglin** [comment]
Just one more review needed on this one
@pmorie @n3wscott

**Pull request merged**
