### PR TITLE
Make instanceID and bindingID unique non-empty strings

### PR DESCRIPTION
**Pull request by duglin**
Not UUIDs.

Closes: #285

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by angarg12** [comment]
LGTM

**Comment by mattmcneeney** [comment]
In many of the example JSON responses, we have things like:
```
"service_id": "service-guid-here",
"plan_id": "plan-guid-here",
```

Worth changing these too as part of this commit? `service-id-here` for example.

**Comment by duglin** [comment]
@mattmcneeney done

**Comment by angarg12** [comment]
LGTM

**Comment by mattmcneeney** [comment]
LGTM

**Comment by duglin** [comment]
more reviews needed: @avade @vaikas-google @fmui @pmorie

**Comment by fmui** [comment]
LGTM

**Comment by duglin** [comment]
One more needed: @vaikas-google @zrob @pmorie @avade

**Comment by pmorie** [comment]
LGTM

**Pull request merged**
