### PR TITLE
Definition of service plan

### LINKED ISSUE #128: What is a plan?
The term *plan* is mentioned several times in the spec but it isn't clearly defined. It would be good to have it explained in the spec.

### PR DESCRIPTION
**Pull request by shalako**
Fixes #128

### CODE REVIEW

**Comment by zrob** [comment]
can we have this say something more about the relationship between service and service plan?

**Comment by duglin** [comment]
rebasing should fix the travis failure

**Comment by mattmcneeney** [comment]
@shalako want to give this another rebase?

**Comment by shalako** [comment]
closing in favor of #286

**Pull request closed without merging**
