### PR TITLE
Fix typo for cost unit example

### PR DESCRIPTION
**Pull request by jbowes**

### CODE REVIEW

**Comment by jbowes** [comment]
The corp CLA for https://github.com/manifoldco should be all set now, if someone can twiddle this PR to get the clabot to notice :)

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
hmm still a CLA issue

**Comment by duglin** [comment]
need CLA

**Comment by jbowes** [comment]
The CLA should *actually* be all set now! Can someone get the bot to notice it?

**Comment by duglin** [comment]
phew!  :-)

LGTM

**Comment by angarg12** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Comment by pmorie** [comment]
LGTM

**Pull request merged**
