### PR TITLE
Remove reference to "marketplace database"

### PR DESCRIPTION
**Pull request by duglin**
See https://github.com/openservicebrokerapi/servicebroker/pull/354#pullrequestreview-74780407

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by mattmcneeney** [comment]
So fast! 👏  LGTM

**Comment by avade** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Comment by fmui** [comment]
LGTM

**Pull request merged**
