### PR TITLE
Release Proposal: v2.17

### PR DESCRIPTION
**Pull request by rsampaio**
Announcing a new release candidate as described in the
  [Release Process](https://github.com/openservicebrokerapi/servicebroker/blob/master/CONTRIBUTING.md#release-process).

  **Release version**: v2.17
  **Release RC SHA**: c619d7165a469b333442bc2d20cc934dc0f7ea69
  **Target release date**: 2022-07-26

  The one-week
  [Review Process](https://github.com/openservicebrokerapi/servicebroker/blob/master/CONTRIBUTING.md#review-process)
  will be triggered on the next weekly call.

### CODE REVIEW

**Review by avilupu — APPROVED** [review]

**Comment by rsampaio** [comment]
@Samze @jberkhahn @gberche-orange We need a couple more approvals here to cut this release, are you guys able to approve? Thanks!

**Comment by gberche-orange** [comment]
this release LGTM (however I'm not an approved reviewer).

**Comment by zoharyehezkely** [comment]
Hi, 
Any update regarding the release?

Thanks,
Zohar.

**Comment by rsampaio** [comment]
@tinygrasshopper or @jberkhahn we still need a +1 to complete this release, if any of you are available I would appreciate a review.

Thanks @gberche-orange, for some reason I thought you joined the PMC team and we should also fix that :)

**Comment by rsampaio** [comment]
@zoharyehezkely it is in progress, we need one more approval from the PMC members to complete the release, it should happen soon.

**Comment by tinygrasshopper** [comment]
@pivotal-marcela-campo any thoughts on the release?

**Comment by Samze** [comment]
LGTM, would like @pivotal-marcela-campo to give it a thumbs up from the CF side before approval

**Comment by pivotal-marcela-campo** [comment]
@Samze @tinygrasshopper I am okay with this release.

**Review by tinygrasshopper — APPROVED** [review]

**Review by Samze — APPROVED** [review]

**Comment by zoharyehezkely** [comment]
Perfect,
Now that we have 3 approvers what is the next step?
Will it be automatically merged?

Thanks,
Zohar.

**Comment by rsampaio** [comment]
An update on this release: looks like TravisCI is not running the validation step required, I couldn't find a reason why this is failing or not triggering and I am investigating, as soon as we get the CI to pass I will merge this and complete the release.

@pivotal-marcela-campo maybe you have the permission to check the travisCI account for cloudfoundry, I suspect this is related to a plan migration that happened in Travis and they now require a plan to build projects.

**Comment by pivotal-marcela-campo** [comment]
@rsampaio Looking into this

**Comment by zoharyehezkely** [comment]
Hi,

Any updates?

Thanks,
Zohar.

**Comment by rsampaio** [comment]
@avilupu @Samze @tinygrasshopper CI caught a lower case reference and I just fixed, I may need your approvals again, sorry about that!

**Review by Samze — APPROVED** [review]

**Review by avilupu — APPROVED** [review]

**Review by tinygrasshopper — APPROVED** [review]

**Comment by zoharyehezkely** [comment]
Hi @rsampaio,

Are we good for merging?

Thanks,
Zohar

**Comment by rsampaio** [comment]
@pivotal-marcela-campo Can you make me admin of this repo? Apparently this travis problem is a known issue and a fix is documented here but requires admin to enable protected branches: https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by pivotal-marcela-campo** [comment]
@rsampaio Thanks for the instructions, was under the impression that Travis was fixed after assigning a plan and importing the repos. I had now configured the check in this repo, working now.

**Comment by zoharyehezkely** [comment]
Thank you all very much

**Pull request merged**
