### PR TITLE
Add missing periods to "description" examples - for consistency

### LINKED ISSUE #390: Error AsyncRequired has a period for description, but not on ConcurrencyError. Pick one.
For `description`, please see: 

```
{
  "error": "AsyncRequired",
  "description": "This Service Plan requires client support for asynchronous service operations."
}
```

vs

```
{
  "error": "ConcurrencyError",
  "description": "Another operation for this Service Instance is in progress"
}
```

### PR DESCRIPTION
**Pull request by duglin**
#And add a new tool to check for it

Closes #390

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by mattmcneeney** [comment]
Wonderful stuff! LGTM

**Comment by jmrodri** [comment]
LGTM

**Comment by fmui** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Comment by n3wscott** [comment]
LGTM

**Comment by arschles** [comment]
LGTM

**Comment by angarg12** [comment]
LGTM

**Pull request merged**
