### PR TITLE
Fix an inconsistency introduced in v2.14

### LINKED ISSUE #508: Should platforms always send deprovision request when failed to update the service instance?
## Background
As the spec says:
`If the successful response includes a state of failed then the Platform MUST send a deprovision request to the Service Broker to prevent an orphan being created on the Service Broker`.

## Problem
Here is a use case below:
Service Broker A is published for providing volume service. After user B provisioned a volume service instance, he wants to resize the volume by calling `UpdateInstance` method. Then for some reasons A fails to complete update operation and it has to return `failed` state in the response of polling last operation. According to current spec definition, platform will deprovision the volume service instance automatically, but it is unacceptable for B because it would cause data loss.

## Proposed solution
For this specific scenario, I think both platform and service brokers could do some work to avoid the problem:
* Add a `state` of `rolled back` with the response of polling last operaion to indicate the repair work of service brokers
* Any service broker which supports rolling back feature MAY return this state to inform platforms everything is fine even though the update operation fails
* Platform should  perceive this state and keep the original parameter of service instance

### LINKED ISSUE #563: Is the 2.14 spec contradictory around orphan mitigation?
Hey all,

I'm trying to understand the orphan mitigation sections of the specification and right now it seems to be contradictory. There may be more cases, but the sections that jumped out to me were 4** status code section in the [orphans](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphans) section and the instructions on what to do under certain response codes from the [provision operation](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-3)

The relevant snippets of text are:

| Status Code Of Service Broker Response | Platform Interpretation Of Response | Platform Initiates Orphan Mitigation? |
| --- | --- | --- |
| ... | ... | ... |
| All other 4xx | Request rejected | No |
| ... | ... | ... |

vs.

> Responses with any other status code MUST be interpreted as a failure and a deprovision request MUST be sent to the Service Broker to prevent an orphan being created on the Service Broker

where status codes defined in the 4** range are 400, 409, and 422.

Am I missing something here like the table is generic and can be overridden by specific endpoint instructions, or is this contradictory?

Thanks,

Will

### PR DESCRIPTION
**Pull request by duglin**
Inconsistency introduced by: https://github.com/openservicebrokerapi/servicebroker/pull/541

Fixes #563
Fixes #508 

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by duglin** [comment]
@leonwanghui thanks, I updated the first comment

**Comment by duglin** [comment]
@mattmcneeney @pmorie @n3wscott @zrob review?

**Comment by gberche-orange** [comment]
@duglin I believe the text `If the response contains "state": "failed" then the Platform MUST send a deprovision request to the Service Broker to prevent an orphan being created on the Service Broker. However, while the Platform will attempt to send a deprovision request, Service Brokers MAY automatically delete any resources associated with the failed bind request on their own.`  introduced by #354 into the "Polling Last Operation for Service Instances" section still remains:

https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-1

I understand this text should be removed as this will negatively impacts service instance update failures as reported by @leonwanghui in #508 when broker `last operation for service instance` endpoint responds with a 200 status with a `failed` body. I'd then suggest to reopen #508

**Comment by duglin** [comment]
@gberche-orange nice catch!! I opened https://github.com/openservicebrokerapi/servicebroker/pull/591 to try to address it

**Pull request merged**
