### PR TITLE
GET instance/bindings MAY not return parameters

### PR DESCRIPTION
**Pull request by jberkhahn**
Just making this explicit.

### CODE REVIEW

**Comment by mattmcneeney** [comment]
Hey @jberkhahn - what was the reasoning behind making this more explicit?

**Comment by duglin** [comment]
We got some questions from our folks about whether or not they were allowed to exclude sensitive info passed as parameters. They didn't want to violate the spec by not returning all params if that's what the spec was mandating.

**Comment by duglin** [comment]
LGTM

**Comment by fmui** [comment]
LGTM

**Comment by zrob** [comment]
lgtm

**Pull request merged**
