### PR TITLE
Making headers for version more consistent.

### PR DESCRIPTION
**Pull request by n3wscott**
The spec does not use headers in the cURL examples in a consistent way, fixed this.

### CODE REVIEW

**Comment by duglin** [comment]
once CLA is signed, LGTM

**Comment by n3wscott** [comment]
Sorry, can someone reopen this? I now have my Google Org public.

**Comment by duglin** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/openservicebrokerapi/servicebroker/pull-request/325/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=openservicebrokerapi/servicebroker)

**Comment by n3wscott** [comment]
@mattmcneeney can you close/reopen this PR for me to get the build to work. I think now that my master is up to date it should be ok.

**Comment by mattmcneeney** [comment]
Thanks @n3wscott LGTM

**Pull request merged**
