### PR TITLE
Make the casing of our table headers consistent

### PR DESCRIPTION
**Pull request by duglin**
Admitting you have a problem is the first step towards recovery.

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by mattmcneeney** [comment]
LGTM x 100000

**Comment by avade** [comment]
Is @duglin paid per character? 

LGMT :)

**Comment by duglin** [comment]
2 more reviews needed

**Comment by vaikas-google** [comment]
LGTM

**Comment by jmrodri** [comment]
LGTM

**Comment by mattmcneeney** [comment]
LGTM

**Comment by zrob** [comment]
LGTM

**Pull request merged**
