### PR TITLE
osb-checker seems written in JS not in golang

### PR DESCRIPTION
**Pull request by felixfriedrich**
**What is the problem this PR solves?**
The description mentioned the wrong language being used.

### CODE REVIEW

**Comment by leonwanghui** [comment]
Hi, the golang code is currently located in dev branch, and it has supported for v2.14 spec with MVP

**Comment by felixfriedrich** [comment]
@leonwanghui The `dev` branch doesn't seem to be public.

**Comment by leonwanghui** [comment]
@felixfriedrich Yes currently the default branch is `master` branch, but we are planning to merge dev branch into master branch, and by then you will see the golang project.

**Comment by leonwanghui** [comment]
image
@mattmcneeney I'm afraid that it can't not be merged directly because of commits difference, do you have some suggestion? Thanks!

**Comment by mattmcneeney** [comment]
@leonwanghui We can probably move the lastest master to a backup branch and then reset it to point at the top of the dev branch. Is the dev branch ready to be master?

**Comment by mattmcneeney** [comment]
@leonwanghui What do you think of the above idea?

**Comment by leonwanghui** [comment]
@mattmcneeney I think it's ready, if anyone others has no opinion, please do it : )

**Comment by mattmcneeney** [comment]
@leonwanghui I've updated the master branch with what was on dev and created a backup branch!

That means the master of osb-checker is written in golang and we can close this PR

**Pull request closed without merging**
