### PR TITLE
Spec says the operation returned with `202` for in-progress instance work should be the same as was returned by the original request.

### PR DESCRIPTION
**Pull request by khipkin**
Partially addresses #453.

Instance provisioning, updating, and deprovisioning response sections now specify that, when 202 is returned in response to duplicate requests while the work is still in progress, the operation ID returned should match that of the original response.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
Hopefully, easy review - 3 needed

**Comment by duglin** [comment]
Instead of saying "Operation ID" the WG would prefer something like "The `operation` string..." just so people don't think we're implying it must be a GUID

**Comment by khipkin** [comment]
Done!

**Comment by n3wscott** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
2 more easy reviews needed

**Comment by fmui** [comment]
LGTM

**Comment by jmrodri** [comment]
LGTM

**Comment by zrob** [comment]
lgtm

**Comment by mattmcneeney** [comment]
LGTM

**Pull request merged**
