### PR TITLE
Fix typo guid -> instance_id

### PR DESCRIPTION
**Pull request by pmorie**
...to make the section self-consistent.

### CODE REVIEW

**Comment by duglin** [comment]
There sre other spots,did you want to fix those too?

**Comment by pmorie** [comment]
Actually, yes, I missed one

**Comment by angarg12** [comment]
LGTM

**Comment by shalako** [comment]
LGTM

**Comment by shalako** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Pull request merged**
