### PR TITLE
Added a missing 'of'

### PR DESCRIPTION
**Pull request by jenspinney**
Minor typo fix.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/openservicebrokerapi/servicebroker/pull-request/357/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=openservicebrokerapi/servicebroker)

**Comment by angarg12** [comment]
LGTM

**Comment by mattmcneeney** [comment]
LGTM

**Pull request merged**
