### PR TITLE
Use non-underscore filenames

### PR DESCRIPTION
**Pull request by duglin**
Replaces #140 

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by duglin** [comment]
@shalako I assume using a link for _release-notes.md is ok, right?

**Comment by martinmaly** [comment]
Thanks, Doug!

**Comment by angarg12** [comment]
LGTM

**Comment by shalako** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Comment by duglin** [comment]
Since google isn't part of the pullapprove yaml yet I'll self-LGTM to cover the missing vote.

**Comment by duglin** [comment]
LGTM

**Pull request merged**
