### PR TITLE
Create logo.svg

### PR DESCRIPTION
**Pull request by guilhem**
Current logo in this repo are in PNG, I needed one in SVG.
I found one on landscape CNCF but objects wasn't shapes but bezier _(not that much)_ circles.

I created a minimal SVG logo with Inkscape using as many clones as possible to reduce size.

Maybe it can help someone.

### CODE REVIEW

**Comment by mattmcneeney** [comment]
Hey @guilhem Thank you for taking the time to create this SVG version of the OSBAPI logo!

Would you be able to sign the CLI as linked above so we can get this merged? Thank you.

**Comment by guilhem** [comment]
@mattmcneeney it should be ok... I did it when opening PR

**Comment by mattmcneeney** [comment]
OK cool - let me try closing and opening this PR to see if it picks it up

**Comment by mattmcneeney** [comment]
Looks like that worked. Thanks @guilhem !

**Pull request merged**
