### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by mattmcneeney**
Travis CI is breaking because of a link issue for openservicebrokerapi.org

We should move the logo to here so we're not dependent on that site being up. Note that the logo URL won't work until this is merged.

### CODE REVIEW

**Comment by mattmcneeney** [comment]
@avade @angarg12 @shalako @pmorie @duglin

**Comment by angarg12** [comment]
Should we close #309 in favor of this one?

**Comment by mattmcneeney** [comment]
@angarg12 I hadn't actually seen #309 ! Sorry!

Up to you. I'd probably vote to add the logo to the repo, but I'm not overly fussed.

**Comment by duglin** [comment]
Don't care which we point to.
LGTM

**Comment by angarg12** [comment]
LGTM

**Comment by avade** [comment]
lgtm

**Comment by vaikas-google** [comment]
LGTM

**Pull request merged**
