### PR TITLE
Clarify conflict case where provisioning or binding is in progress

### PR DESCRIPTION
**Pull request by rwwilden**
When provisioning or binding is in progress, it is possible in theory to send another provisioning or binding request with different parameters. The spec does not say how to handle this case but it makes sense to send a `409 Conflict` response in this case.

### CODE REVIEW

**Comment by jberkhahn** [comment]
Hey there!

This looks interesting, but we need you to sign the CLA first.

**Comment by rwwilden** [comment]
@jberkhahn working on it 👍 
Was confinced I already signed a CLA a long time ago but probably mistaken.

**Comment by mattmcneeney** [comment]
Closing and reopening to retrigger CLA bot

**Comment by rwwilden** [comment]
I just signed and sent the CLA.

**Pull request merged**
