### PR TITLE
Use full URLs in profile.md

### PR DESCRIPTION
**Pull request by mattmcneeney**
CF docs pull this file in automatically, however the links don't work unless they are absolute. This will fix this issue.

### CODE REVIEW

**Comment by mattmcneeney** [comment]
@shalako @duglin @vaikas-google @pmorie @angarg12 
Would appreciate help getting this merged (if no objections) so we can get our CF docs updated :)

**Comment by angarg12** [comment]
LGTM

**Comment by shalako** [comment]
Just want to confirm we're going to start linking out to the OSBAPI repo from CF docs rather than use relative links...

**Comment by mattmcneeney** [comment]
Yep that's right. The other option would be to link to profile.md.html.erb,
but something tells me that isn't a good idea!

**Comment by mattmcneeney** [comment]
As per @duglin's comment on the other similar PR, this isn't a suitable solution, so closing.

**Pull request closed without merging**
