### PR TITLE
Update the supported version of osb-checker

### PR DESCRIPTION
**Pull request by leonwanghui**
Signed-off-by: leonwanghui <wanghui71leon@gmail.com>

**What is the problem this PR solves?**
See https://github.com/openservicebrokerapi/osb-checker/issues/43#issuecomment-547807440

**Checklist:**
- [ ] The [swagger.yaml](swagger.yaml) doc has been updated with any required changes
- [ ] The [openapi.yaml](openapi.yaml) doc has been updated with any required changes

### CODE REVIEW

**Comment by leonwanghui** [comment]
Sorry I have tried that, it seems that I can't register the account because my company wasn't involved.

**Comment by mattmcneeney** [comment]
Looking into this now...

**Comment by WillsonHG** [comment]
@leonwanghui @mattmcneeney Leon I've made sure you are white listed for contribution now on the new EasyCLA bot check. Can you please try to sign again and select "CFF Migration" from the list of companies? You should then be presented with a check box for verification. It says the bot will be triggered with a refresh of the page, but you may also have to close and reopen this pr if that doesn't work.

**Comment by mattmcneeney** [comment]
@leonwanghui Please could you retry the EasyCLA signing process again?

**Comment by leonwanghui** [comment]
Hi @mattmcneeney, it seems that my company has not signed yet, could you take a look at it?
image

**Comment by mattmcneeney** [comment]
@chipchilders @WillsonHG Please could you advise what process we should follow here for @leonwanghui from Huawei?

**Comment by WillsonHG** [comment]
@leonwanghui  @mattmcneeney  The work around for that is to select "CFF Migration" as your company instead of Huawei. You've been whitelisted there as a part of Huawei.

**Comment by leonwanghui** [comment]
@WillsonHG @mattmcneeney I think it's done, much thanks for offering the help!

**Comment by mattmcneeney** [comment]
@fmui please review :)

**Pull request merged**
