### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mattmcneeney**
`properties` should be `parameters`.

### CODE REVIEW

**Comment by angarg12** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by mattmcneeney** [comment]
Easy one @avade @pmorie @shalako @fmui

**Comment by duglin** [comment]
@vaikas-google @pmorie @avade @fmui easy review

**Comment by vaikas-google** [comment]
LGTM

**Comment by shalako** [comment]
LGTM

**Pull request merged**
