### PR TITLE
Check for double spaces after periods

### PR DESCRIPTION
**Pull request by duglin**
Yes I'm *that* ODC :-)

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by n3wscott** [comment]
Boo. No one uses double spaces after periods.

**Comment by duglin** [comment]
I was taught double spaces ages ago....

**Comment by pmorie** [comment]
> Yes I'm that ODC :-)

Not sure I believe that ^^

**Comment by angarg12** [comment]
LGTM

**Comment by n3wscott** [comment]
> I was taught double spaces ages ago....

And then schools stopped teaching that, but mention it as an antiquated practice.

**Comment by duglin** [comment]
easy review

**Comment by mattmcneeney** [comment]
LGTM (at last!)

**Comment by n3wscott** [comment]
LGTM

**Comment by avade** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/openservicebrokerapi/servicebroker/pull-request/406/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=openservicebrokerapi/servicebroker)

**Pull request merged**
