### PR TITLE
remove old files

### PR DESCRIPTION
**Pull request by mattmcneeney**
How do people feel about removing these old files? I checked the [page traffic](https://github.com/openservicebrokerapi/servicebroker/graphs/traffic) for this repo and these two don't appear at all under the popular content tab, so they haven't had _many_ views recently (I can't determine if they've had _any_ views though).

I know the [CF docs](https://docs.cloudfoundry.org/services/) no longer link to those files.

### CODE REVIEW

**Comment by duglin** [comment]
yes please!
LGTM

**Comment by fmui** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Comment by pmorie** [comment]
LGTM

**Pull request merged**
