### PR TITLE
Fix master

### PR DESCRIPTION
**Pull request by duglin**
RFC checker wasn't returning non-zero on error.
Fix "may" in the spec.

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by duglin** [comment]
Easy review!

**Comment by angarg12** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Comment by avade** [comment]
lgtm

**Comment by duglin** [comment]
Sorry - another round of L G T Ms are needed, I added another one-line changed.  I just noticed that master was busted again - the last PR merged removed a table header row by mistake.

Ping @angarg12 @vaikas-google @avade @pmorie 

Quick-n-easy review

**Comment by angarg12** [comment]
LGTM 👍

**Comment by avade** [comment]
lgtm

**Comment by vaikas-google** [comment]
LGTM

**Comment by duglin** [comment]
Can I get one more L.G.T.M. on this one? I'd really like to fix master :-)

**Comment by mattmcneeney** [comment]
@pmorie @shalako @zrob Looking for one more L G T M. Release deadline is approaching fast!

**Comment by pmorie** [comment]
LGTM

**Pull request merged**
