### PR TITLE
Fix typo in bind_resource

### PR DESCRIPTION
**Pull request by pmorie**
... it was mispelled `bind-resource` in one place.

### CODE REVIEW

**Comment by angarg12** [comment]
LGTM

**Comment by avade** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

We really need to fix it so the spec keeps like down to 80 chars, it'll be so much easier to spot diffs after that. :-)  Plus, if we do end up using swagger/yaml then it'll look nicer too.

**Comment by avade** [comment]
@zrob @shalako @fmui @vaikas-google we need one more lgtm here

**Comment by zrob** [comment]
LGTM

**Pull request merged**
