### PR TITLE
[WIP] to swap google doc for mermaidjs diagrams

### PR DESCRIPTION
**Pull request by JJediny**
FOR DISCUSSION ONLY:
See #374

### CODE REVIEW

**Comment by avade** [comment]
We use mermaidjs for diagrams in Pivotal docs and it is much easier to maintain vs static pictures. 

In terms of the styling here, font and sizing could be smaller.

**Comment by n3wscott** [comment]
I like this idea. I have been a graphviz user for a long time, programmatic charts are great.

**Comment by mattmcneeney** [comment]
Hey @JJediny I'm still keen to move this into the spec. Are there any outstanding issues with this?

**Comment by duglin** [comment]
During this week's call we discussed this and there was no objection with heading this direction.

**Comment by duglin** [comment]
@JJediny  What do we need to do to move this one forward? Does someone need to create some kind of build process to build the images as part of a PR?  Is this something you want to do?

**Comment by JJediny** [comment]
The next few weeks don't look good for me doing much proactive work to support this; but want to help it see it through. Would like someone to propose the ideal workflow for updating (either as steps to re-gen or build into CI).

**Comment by duglin** [comment]
Any update on this? If no one has the time to work on it then I'm wondering if we should close it, or move it back to just an issue and then reopen the PR if/when someone has time.

**Comment by n3wscott** [comment]
Reopen if there is need.

**Comment by mattmcneeney** [comment]
We'll need to update the [Workflows diagram](https://github.com/openservicebrokerapi/servicebroker/blob/master/diagram.md) soon to cover async bindings!

**Pull request closed without merging**
