### PR TITLE
Add OpenAPI doc to v2.13 release branch

### PR DESCRIPTION
**Pull request by mattmcneeney**
Then we can link to a rendered version of the OpenAPI spec. from the readme for v2.13 (see #420)

### CODE REVIEW

**Comment by angarg12** [comment]
Should we wait to merge #417 to have the latest copy?

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
2 more reviews needed

**Comment by avade** [comment]
LGTM

**Comment by fmui** [comment]
LGTM

**Pull request merged**
