### PR TITLE
Allow periods in the name field

### PR DESCRIPTION
**Pull request by mihnjong**
Service class and plan names can contain periods (".").

closes: #442

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
removing L GTM due to CLA not being there.
@mihnjong can you sign the CLA?

**Comment by mihnjong** [comment]
For this change, I worked as a Google employee. which form should I sign?

**Comment by duglin** [comment]
@chipchilders can you answer @mihnjong's question? I'm not familiar enough with the CLA process.

**Comment by chipchilders** [comment]
@mihnjong you need to be a publicly listed member of the GoogleCloudPlatform GH org for the Google CLA to cover your contribution. That's the GH org that Google identified as the right org for us to use in the bot. Alternatively you can follow the ICLA instructions to sign as yourself (which assumes you have your employer's permission to do so).

**Comment by mihnjong** [comment]
@n3wscott helped me to make visible my organization status. I guess the PR is good to go now :)

**Comment by chipchilders** [comment]
close / open to kick the bot

**Comment by chipchilders** [comment]
close / open to kick the bot

**Comment by chipchilders** [comment]
@mihnjong still not publicly listing you as part of the GoogleCloudPlatform GH org. I only see the Google GH org in your profile.

**Comment by n3wscott** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
2 more needed

**Comment by fmui** [comment]
LGTM

**Comment by mattmcneeney** [comment]
LGTM but conflicts need fixing @mihnjong

**Comment by duglin** [comment]
@mihnjong  can you rebase to fix the conflict?

**Comment by n3wscott** [comment]
LGTM

**Comment by subhankarc** [comment]
Hi,

Will this improvement be part of v2.13? Eagerly waiting for it. We also have a similar use-case where plan names contain version number which includes periods.

Regards,
Subhankar

**Comment by duglin** [comment]
@mihnjong can you rebase please?

@subhankarc I expect it to be part of v2.13 but when it will appear in Kube and CF is up to those projects. Once approved, I think Kube should be able to add it within days, but I can't speak for CF. @mattmcneeney

**Comment by duglin** [comment]
@mihnjong I did the rebase for you - hope that's ok

**Comment by duglin** [comment]
LGTM

3 more reviews needed

**Comment by n3wscott** [comment]
LGTM

**Comment by fmui** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Comment by mihnjong** [comment]
Sorry.. I was swamped with other work. Thanks @duglin !

**Pull request merged**
