### PR TITLE
Fixing minor typos.

### PR DESCRIPTION
**Pull request by n3wscott**
Reading the spec for the first time, these jumped out as minor mistakes.

### CODE REVIEW

**Comment by duglin** [comment]
once the CLA is signed, I'm ok with these edits.
LGTM

**Comment by duglin** [comment]
hmm @mattmcneeney shouldn't those links be good now?

**Comment by mattmcneeney** [comment]
@duglin yes they should. I think the problem may be that this branch needs to be rebased on master?

**Comment by n3wscott** [comment]
Ok let me try to rebase.

**Comment by n3wscott** [comment]
I think I had rebased already but I had not pushed my local master to github. Done now.

**Comment by mattmcneeney** [comment]
Looks like it's going to pass this time :)

**Comment by vaikas-google** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by mattmcneeney** [comment]
LGTM

**Comment by angarg12** [comment]
LGTM

**Pull request merged**
