### PR TITLE
Markdown can not have a class

### PR DESCRIPTION
**Pull request by jpeeler**
The application of the note class makes the markdown link text render as plain
text and not as a link.

### CODE REVIEW

**Comment by duglin** [comment]
Did you push the right change? It doesn't seem to match the text of the issue

**Comment by jpeeler** [comment]
I did push the correct change. The markdown link "[Catalog](#catalog-management)" was removed, which was tagged with the paragraph element and note class. Maybe it's actually just being content in a paragraph that doesn't cause the link to show up, not sure.

**Comment by duglin** [comment]
Ah ok I see now.  The anchor is still there (see line 107, in my copy anyway).  I think perhaps the right fix is to remove the <p> tag instead.

**Comment by mattmcneeney** [comment]
Hey @jpeeler. Is this problem arising when pulling these docs into platform-specific docs?

**Comment by jpeeler** [comment]
@mattmcneeney The problem is when rendered on github, though I assume the same would apply with any markdown rendering elsewhere. https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#binding

**Comment by mattmcneeney** [comment]
@jpeeler so it is, I didn't realise that. We'd had some trouble sync'ing these docs with other tools so just wanted to make sure it wasn't another problem along those lines.

This change looks good to me.

**Comment by duglin** [comment]
I don't think we should remove the href, let's remove the \<p\> and class instead. Its odd that we have a class w/o its definition anyway.

**Comment by shalako** [comment]
I'm ok with removing the `<p>` but then we should do it for another one in the spec also.

**Comment by mattmcneeney** [comment]
I'm OK with this too. This was for the CF docs, but we are moving to a solution where this won't be required.

**Comment by duglin** [comment]
@jpeeler you ok with making the proposed change? If you don't have time I can do it.

**Comment by jpeeler** [comment]
@duglin the latest commit made the change, I think it's good to go.

**Comment by duglin** [comment]
@jpeeler I think there are 4 \<p\> / Notes in the spec that would fall into this category, do you want to do the others too?

**Comment by jpeeler** [comment]
Sorry didn't realize you wanted them all gone, but now they are!

**Comment by duglin** [comment]
excellent - thanks!
LGTM

**Comment by shalako** [comment]
LGTM

**Comment by angarg12** [comment]
LGTM

**Comment by duglin** [comment]
need one more easy L.G.T.M

**Comment by duglin** [comment]
@pmorie?

**Comment by avade** [comment]
lgtm

**Pull request merged**
