### PR TITLE
Remove terms from profile, link to spec terminology

### PR DESCRIPTION
**Pull request by n3wscott**
We had talked about making a new file for terms and linking from both, I think they should be in the spec like this. Thoughts?

### CODE REVIEW

**Comment by duglin** [comment]
Even though I liked having a copy of them in here, I can live with just the ref.
LGTM

**Comment by avade** [comment]
LGTM

**Comment by fmui** [comment]
LGTM

**Comment by mattmcneeney** [comment]
LGTM

**Pull request merged**
