### PR TITLE
Tidy up release process

### PR DESCRIPTION
**Pull request by mattmcneeney**
A couple of amendments I think we should make to the release process, just to make it crystal clear.

### CODE REVIEW

**Comment by angarg12** [comment]
LGTM

**Comment by avade** [comment]
Thanks for the followup @mattmcneeney 

LGTM

**Comment by duglin** [comment]
LGTM

**Comment by mattmcneeney** [comment]
One more pls @pmorie

**Comment by avade** [comment]
@zrob @shalako if you can take a look we need one more L.G.T.M

**Pull request merged**
