### PR TITLE
Issue 249 - modify "uniqueness" requirements

### PR DESCRIPTION
**Pull request by duglin**
Service providers can't really guarantee service name unqiueness
so we can't really require it - but we can provide some guidance.

Closes: #249

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by duglin** [comment]
@mattmcneeney I tried to address your comment ( https://github.com/openservicebrokerapi/servicebroker/issues/249#issuecomment-310997977 ) - see if that covers it.

**Comment by mattmcneeney** [comment]
@duglin This looks great. I think this makes the field usage much clearer. Go go go!

**Comment by shalako** [comment]
LGTM

**Comment by angarg12** [comment]
Needs rebase.

**Comment by duglin** [comment]
rebased!

**Comment by angarg12** [comment]
Travis is failing!

**Comment by duglin** [comment]
Ah, that will be fixed by https://github.com/openservicebrokerapi/servicebroker/pull/264
but I'll make that same one-line fix here too just so travis is happy.

**Comment by avade** [comment]
lgtm

**Comment by angarg12** [comment]
LGTM

**Comment by shalako** [comment]
LGTM

**Comment by duglin** [comment]
one more l.g.t.m needed.  @pmorie @zrob ?

**Comment by zrob** [comment]
lgtm

**Pull request merged**
