### PR TITLE
Change example to match field order of request body

### PR DESCRIPTION
**Pull request by jpeeler**
This doesn't have to be merged, but slightly helps readability I think.

### CODE REVIEW

**Comment by duglin** [comment]
If we do reorder things,i think I'd prefer to change the table so that context is first mainly because to me it's like global info (almost like a header) so putting it first kind of separates it a bit from the info of the real data of the request.

**Comment by mattmcneeney** [comment]
The other fields are also getting deprecated at some point in the future, but I'm happy with reordering things for readability.

**Comment by shalako** [comment]
LGTM

Service and plan ids at the top work for me.

**Comment by pmorie** [comment]
LGTM

**Comment by angarg12** [comment]
LGTM

**Comment by shalako** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Pull request merged**
