### PR TITLE
Change object to JSON object in tables

### PR DESCRIPTION
**Pull request by mattmcneeney**
Consistency!

### CODE REVIEW

**Comment by duglin** [comment]
image

LGTM

**Comment by n3wscott** [comment]
The spec calls out when objects should be encoded as JSON. JSON is an encoding not an object type right? It seems like defining the type as just object is clear in the context. To my eye defining the type as 'JSON object' seems strange.

**Comment by duglin** [comment]
my 2 cents... I don't care which we show in the tables, but let's be consistent. Right now we alternate based on a reason that I don't think most users would pick on.

**Comment by mattmcneeney** [comment]
I agree with both of the above comments. JSON object seemed a little odd to
me, but I wanted consistency across the spec. I’d be happy to change all to
object if folks are happy with that?

**Comment by duglin** [comment]
go for it

**Comment by mattmcneeney** [comment]
Updated @duglin @n3wscott

**Comment by n3wscott** [comment]
I think that reads better, and perhaps one last edit for this could be in the description field, sometimes it reads 'object' and sometimes 'JSON object'. I think it does make sense to have JSON in the description, example:

'An opaque object...' to 'An opaque JSON object...', etc

**Comment by duglin** [comment]
LGTM
I'm ok w/ or w/o scott's latest suggestion.

**Comment by vaikas-google** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Comment by angarg12** [comment]
LGTM

**Comment by avade** [comment]
lgtm

**Pull request merged**
