### PR TITLE
Remove some uses of "will" in the spec

### LINKED ISSUE #411: try to remove usages of "will"
E.g.  Request timeouts, responses with any other status code, or malformed response bodies will be interpreted as failures.

I'm not sure if this is a pseudo MUST or not. Let's try to reword these things. So, for example, this one might be:
Request timeouts, responses with any other status code, or malformed response bodies MUST be interpreted as failures

### PR DESCRIPTION
**Pull request by duglin**
Many of these were psuedo-normative MUSTs so I made them real MUSTs

Closes #411

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by mattmcneeney** [comment]
LGTM

**Comment by avade** [comment]
LGTM!

**Comment by duglin** [comment]
2 more reviews needed

**Comment by pmorie** [comment]
Kind of surprised these went undetected for so long. LGTM

**Pull request merged**
