### PR TITLE
Update the pullapprove contributor list

### PR DESCRIPTION
**Pull request by avade**
Changed to reflect the changed PMC members

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by avade** [comment]
Before we merge we need to add @vaikas-google & @zrob as contributors if we consider they switch-in ratified by the PMC.

cc @shalako @chipchilders

**Comment by shalako** [comment]
+1

**Comment by pmorie** [comment]
Looks like the yaml is invalid.

**Comment by angarg12** [comment]
@pmorie it looks like @vaikas-google and @zrob are not collaborators of the project. From pullapprove.

> "{'required': 1, 'members': ['duglin', 'vaikas-google', 'shalako', 'angarg12', 'pmorie', 'petereberlein', 'zrob', 'avade']}" is an invalid value for reviewers: 'vaikas-google' is not a collaborator of this repo, 'zrob' is not a collaborator of this repo

**Comment by duglin** [comment]
@chipchilders could you add them? I checked and I don't think I have admin rights on the repo to do so.

**Comment by avade** [comment]
@chipchilders could you take a look at this issue and add @vaikas-google and @zrob. We can then merge this PR.

**Comment by chipchilders** [comment]
@vaikas-google and @zrob need to accept the invites, but they have been added as contributors

**Comment by angarg12** [comment]
LGTM

**Comment by jmrodri** [comment]
LGTM

**Comment by avade** [comment]
@petereberlein can you give your LGTM then we can merge.

**Comment by petereberlein** [comment]
LGTM

**Pull request merged**
