### PR TITLE
Fix typo - s/as/has/

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by mattmcneeney** [comment]
LGTM

**Comment by fmui** [comment]
LGTM

**Comment by duglin** [comment]
easy review - 2 needed

**Comment by fmui** [comment]
LGTM

**Comment by zrob** [comment]
lgtm

**Comment by jmrodri** [comment]
LGTM :)

**Comment by n3wscott** [comment]
LGTM

**Pull request merged**
