### PR TITLE
Add Huawei Cloud Service Broker Examples

### PR DESCRIPTION
**Pull request by leonwanghui**
Signed-off-by: leonwanghui <wanghui71leon@gmail.com>

@mattmcneeney @duglin @n3wscott

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by mattmcneeney** [comment]
LGTM

**Comment by leonwanghui** [comment]
Two more plz, thanks!

**Comment by zrob** [comment]
lgtm

**Comment by mattmcneeney** [comment]
Merged. Thanks @leonwanghui !

**Comment by leonwanghui** [comment]
Thanks everyone!

**Pull request merged**
