### PR TITLE
remove marketplace and use correct case for Platform

### PR DESCRIPTION
**Pull request by mattmcneeney**
Because I like causing myself pain... but really because I think a "marketplace" is a Platform implementation detail, and we shouldn't have it as part of the specification.

I also took the opportunity to change all occurrences of `platform` to `Platform` as it is a defined term in the spec.

### CODE REVIEW

**Comment by mattmcneeney** [comment]
@n3wscott you should like this one 😄

**Comment by duglin** [comment]
Overall +1 but CI failed

**Comment by angarg12** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by pmorie** [comment]
LGTM

**Pull request merged**
