### PR TITLE
Combine all docs into one

### PR DESCRIPTION
**Pull request by MHBauer**
This is the first step. Having everything in one file reduces the
friction of dealing with individual files. This makes it easier to start
moving and deleting sections from a global perspective.

This is almost a pure copy. There was some rearranging to bring to the
top sections that will probably remain.

Additions of a reference to doc formatting rfc.

Some tables were converted from html to markdown as they were not
rendering correctly. `pandoc --from=html --to=markdown_github`

@duglin @shalako @pmorie @vaikas-google @bmelville et al. Want to hear from everyone, but this shouldn't be very controversial. That comes later!

### CODE REVIEW

**Comment by duglin** [comment]
Lots of edits I want to make in follow-on PR! :-)
LGTM

**Comment by duglin** [comment]
Anyone else care to review?

**Comment by bmelville** [comment]
I'm a little confused as I see only deletes but no adds anywhere. Is this missing the actual unified file?

**Comment by duglin** [comment]
@bmelville github just isn't showing it - click on the 'view' button for each file

**Comment by bmelville** [comment]
Ah yes I see it now, thanks!

**Comment by bmelville** [comment]
LGTM

**Comment by MHBauer** [comment]
That makes two if we want to play by the rules. This is going to conflict with #74 & #96, but it looks simple to copy and paste into the new location.

Thoughts? Time to merge?

**Comment by bmelville** [comment]
Those are both mine, and I plan to wait for you on this and then adapt them to the single file model.

**Comment by duglin** [comment]
@shalako comments?

**Comment by shalako** [comment]
Haven't had a chance to read it yet.

Shannon Coen
Product Manager, Cloud Foundry
Pivotal, Inc.

**Comment by MHBauer** [comment]
I'd like to either merge this or close it. I have changes to propose.

**Comment by duglin** [comment]
@MHBauer patience....  :-)

**Comment by judkowitz** [comment]
LGTM

**Comment by shalako** [comment]
I'd like to comment in context, but I can't figure out how to get to the view of the change I'm used to seeing.

- The broker API has since been versioned to 2.10. Rebase or submit an additional PR with 2.10 changes?

- Why were the sections on the version header and authentication removed? Don't these deserve some explanation? They appear in example curls, but there is no other explanation. How should the broker author know what their responsibilities are?

- With the exception of the table of contents, none of the links work.

- The example response body for Provision contains `"dashboard\_url"`. The backslash should be removed. This may have been in an older version of github.com/cloudfoundry/docs-services but has since been fixed there.

- The first paragraph of the intro for Updating a Service Instance is out of date. I recall rewriting that some time ago. 

- The whole section titled "Manage Application Requests with Route Services" can be removed. This link appears in the index of the current docs, but I've just sent a PR to remove it. This topic is for marketplace end-users (app developers), not for service broker authors. https://github.com/cloudfoundry/docs-services/pull/145

- Remove the whole section titled "Volume Services (Experimental/Obsolete)" and fix the link in TOB for "Volume Services (Experimental)"

- You can remove the section "Using cf curl" under Access Control, as well as instructions to get the api version. I've just submitted a PR to docs-services to do the same. https://github.com/cloudfoundry/docs-services/pull/147

Otherwise, LGTM

**Comment by avade** [comment]
*kind of related*

In v2.10 volume services are no longer experimental.

Note that there was a breaking change for volume services from v2.9 to 2.10
when the "experimental" flag was removed.

As part of this WG I would love to discuss the use of "experimental" API
specs. Not sure that it worked well in this case.

**Comment by duglin** [comment]
per the call today - we'll address any comments/edits via new PRs.
Mainly from Shannon:

The broker API has since been versioned to 2.10. Rebase or submit an additional PR with 2.10 changes?

Why were the sections on the version header and authentication removed? Don't these deserve some explanation? They appear in example curls, but there is no other explanation. How should the broker author know what their responsibilities are?

With the exception of the table of contents, none of the links work.

The example response body for Provision contains "dashboard\_url". The backslash should be removed. This may have been in an older version of github.com/cloudfoundry/docs-services but has since been fixed there.

The first paragraph of the intro for Updating a Service Instance is out of date. I recall rewriting that some time ago.

The whole section titled "Manage Application Requests with Route Services" can be removed. This link appears in the index of the current docs, but I've just sent a PR to remove it. This topic is for marketplace end-users (app developers), not for service broker authors. cloudfoundry/docs-services#145

Remove the whole section titled "Volume Services (Experimental/Obsolete)" and fix the link in TOB for "Volume Services (Experimental)"

You can remove the section "Using cf curl" under Access Control, as well as instructions to get the api version. I've just submitted a PR to docs-services to do the same. cloudfoundry/docs-services#147

**Comment by shalako** [comment]
@duglin Is someone else going to make these changes or should I?

**Comment by duglin** [comment]
@shalako if you can open PRs for them that would be great

**Pull request merged**
