### PR TITLE
Update SPEC.md

### PR DESCRIPTION
**Pull request by shalako**
- adding back sections for version header and authentication
- removed unnecessary backslash in `"dashboard\_url"`
- Intro for Update a Service Instance
- Removed section "Manage Application Requests with Route Services"
- Removed section "Volume Services (Experimental/Obsolete)"
- Removed sections related to using cf curl to manage Access Control

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
@shalako you'll need to sign your commits.

**Comment by shalako** [comment]
> @shalako you'll need to sign your commits.

I don't know how to change commits I've already made. I added another commit and signed it. Good enough?

Is this a CFF requirement? I've never had to do this before.

**Comment by duglin** [comment]
@shalako just rebase/squash your commits down to one and make sure you sign that one - then it should be ok.

**Comment by duglin** [comment]
since we don't have any kind of CLA thing in place DCOs are the next best thing.

**Comment by angarg12** [comment]
LGTM

**Comment by duglin** [comment]
@shalako should we close this?

**Pull request closed without merging**
