### PR TITLE
Fix table checker so it supports sentences in more than just last column

### PR DESCRIPTION
**Pull request by duglin**
Should fix the issue we see in #254

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by angarg12** [comment]
LGTM

**Comment by duglin** [comment]
I'd like to get this one in quickly so other PRs are not blocked by the bug.
@pmorie @vaikas-google @avade @fmui @mattmcneeney

**Comment by mattmcneeney** [comment]
LGTM

**Comment by shalako** [comment]
LGTM

**Comment by mattmcneeney** [comment]
@fmui @pmorie one more needed

**Comment by duglin** [comment]
@zrob @avade @vaikas-google need one more review

**Comment by fmui** [comment]
LGTM

**Pull request merged**
