### PR TITLE
s/clusterID/clusterid/

### LINKED ISSUE #477: clusterID should be cluster_id ?
No other json field inside the OSB spec has caps. It looks like the convention would be `clusterID` -> `cluster_id`.

### PR DESCRIPTION
**Pull request by duglin**
Closes #477

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by MHBauer** [comment]
LGTM, this should be quick to close

**Comment by fmui** [comment]
LGTM

**Comment by jmrodri** [comment]
I prefer clusterid

**Comment by mattmcneeney** [comment]
LGTM

**Comment by MHBauer** [comment]
@n3wscott needs a 'LGTM' not in a reveiwy note.

**Comment by n3wscott** [comment]
@MHBauer not anymore... as told in the meeting, PR review approve works.

**Comment by vaikas-google** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/openservicebrokerapi/servicebroker/pull-request/479/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=openservicebrokerapi/servicebroker)

**Comment by MHBauer** [comment]
well, I zoned out on that.

**Pull request merged**
