### PR TITLE
Be clear about the error when the request is missing required data

### LINKED ISSUE #274: Spec does not define expected status code when required fields are absent

### PR DESCRIPTION
**Pull request by duglin**
I tried to word it so that its not just missing data from the body
but should also cover cases where the URL is missing requird path
components (like instance_id)

Closes #274

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by avade** [comment]
Looks good but Travis has failed.

**Comment by duglin** [comment]
weird, I could have sworn I ran the checker - must not have. Anyway, fixed now - thanks for the poke.

**Comment by angarg12** [comment]
LGTM

**Comment by avade** [comment]
lgtm

**Comment by duglin** [comment]
2 more reviews needed

**Comment by mattmcneeney** [comment]
LGTM

**Comment by mattmcneeney** [comment]
One more @pmorie @fmui

**Comment by duglin** [comment]
@shalako @pmorie @zrob @vaikas-google one more review needed

**Comment by fmui** [comment]
LGTM

**Pull request merged**
