### PR TITLE
Better define what a "CLI-friendly string" is

### PR DESCRIPTION
**Pull request by mattmcneeney**
I don't mind if we want to add a generic definition for this and then change the field type for these two cases, but if everyone is happy with this, I'm fine with it.

Thanks to Laird Nelson for the note about this in slack.

### CODE REVIEW

**Comment by shalako** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by zrob** [comment]
LGTM

**Comment by shalako** [comment]
One more needed

**Comment by angarg12** [comment]
LGTM

**Pull request merged**
