### PR TITLE
Fix formatting of links to CF conventions for metadata

### PR DESCRIPTION
**Pull request by pmorie**
...was formatted incorrectly throughout.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM
but I think some other PR might have removed that text - not sure why though.

**Comment by pmorie** [comment]
@duglin, @mattmcneeney's #74 PR removes it - I am not certain why.  I think we should keep these links.

**Comment by mattmcneeney** [comment]
PR #165 has been updated!

**Comment by duglin** [comment]
@mattmcneeney what part of #165 was updated and to address which comment?

**Comment by mattmcneeney** [comment]
@duglin whoops, push failed, didn't realise! I've [added a commit](https://github.com/openservicebrokerapi/servicebroker/pull/165/commits/88de5f582fec5868ec1ee4496b5980fbfb3f5d1f)

**Comment by duglin** [comment]
@mattmcneeney thanks

**Comment by angarg12** [comment]
Needs rebase.

**Comment by mattmcneeney** [comment]
Nudge @pmorie for a quick rebase

**Comment by angarg12** [comment]
LGTM

**Comment by duglin** [comment]
What's the purpose behind this PR? Do we no longer want to point to those conventions?  There are 2 other spots in the spec where we have that pointer - so it seems we should remove those too, no?  Or, move those conventions into our spec - which I would actually prefer.

**Comment by shalako** [comment]
I agree with Doug; we should move the catalog-metadata file to this repo.

**Comment by duglin** [comment]
@pmorie if you don't have time to do the move let me know and I can add that to this PR if you want.

**Comment by pmorie** [comment]
@duglin @shalako 

> What's the purpose behind this PR? Do we no longer want to point to those conventions? There are 2 other spots in the spec where we have that pointer - so it seems we should remove those too, no? Or, move those conventions into our spec - which I would actually prefer.

At this point, I just want to remove a single link to the conventions that's in the provision parameters request body when it shouldn't be.

**Comment by shalako** [comment]
Looking more closely at the change, we don't need a link to catalog metadata from the context of create parameters. The former is about marketplace catalog display metadata, the latter optional config inputs for the create operation.

LGTM

**Comment by mattmcneeney** [comment]
It'sssss rebase time again!

**Comment by pmorie** [comment]
Rebased

**Comment by shalako** [comment]
LGTM

**Comment by angarg12** [comment]
LGTM

**Comment by pmorie** [comment]
LGTM

**Comment by duglin** [comment]
I thought we agreed no-self-L.G.T.M'ing.

**Comment by pmorie** [comment]
Did we?  I had forgotten.  Looks like it didn't count me anyway.  I'll remove the comment

**Comment by duglin** [comment]
LOL you delete my comment not yours

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
it did actually pick-up your LGT M

**Comment by duglin** [comment]
so waiting for one more

**Comment by shalako** [comment]
LGTM

**Comment by duglin** [comment]
@shalako already got yours

**Pull request merged**
