### PR TITLE
Check case of rfc and terms across lines

### PR DESCRIPTION
**Pull request by duglin**
ping @n3wscott

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by angarg12** [comment]
LGTM

**Comment by mattmcneeney** [comment]
Conflict @duglin !

**Comment by duglin** [comment]
rebased and added logic to look for banned phrases

**Comment by angarg12** [comment]
LGTM

**Comment by avade** [comment]
LGTM

**Comment by vaikas-google** [comment]
LGTM

**Comment by duglin** [comment]
one more review needed

**Comment by mattmcneeney** [comment]
LGTM

**Pull request merged**
