### PR TITLE
Restore spec.md and add symlink to _spec.md

### PR DESCRIPTION
**Pull request by pmorie**
As discussed in today's WG call.

### CODE REVIEW

**Comment by duglin** [comment]
@shalako any chance of adding this symlink to the CF repo or to their build process?

**Comment by shalako** [comment]
I'm checking on whether this will break the CF docs.

**Comment by pmorie** [comment]
Alternately, perhaps the CF team can apply a transformation to the repo
before processing?

**Comment by shalako** [comment]
As of today, the CF docs are now pointing at this repo for the API spec and release notes.

They have tested that their tooling will accommodate the symlink, so this should be safe to merge.

**Comment by pmorie** [comment]
@shalako Rebased

**Comment by angarg12** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by avade** [comment]
LGTM

**Comment by pmorie** [comment]
@shalako @avade can we merge this?  I don't like hitting the button myself.

**Pull request merged**
