### PR TITLE
Latest release should link to spec (not git branch)

### PR DESCRIPTION
**Pull request by mattmcneeney**
Hopefully a simple one. It's a little annoying having to click twice to see the spec.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by avade** [comment]
Good call.

LGTM

**Comment by angarg12** [comment]
LGTM

**Comment by mattmcneeney** [comment]
@pmorie I'm not sure your review comment worked as an LGTM. Could you try again!?

**Comment by vaikas-google** [comment]
LGTM

**Pull request merged**
