### PR TITLE
Add Matt McNeeney to the PMC

### PR DESCRIPTION
**Pull request by avade**
Matt has been voted in and will join the OSBAPI PMC as a dedicated committer.

### CODE REVIEW

**Comment by angarg12** [comment]
We need a change in pullapprove to add Matt to the list.

**Comment by avade** [comment]
Waiting for Matt to accept the invite to the repo.

**Comment by vaikas-google** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by angarg12** [comment]
LGTM

**Comment by avade** [comment]
self lgtm as it's such a small change

**Comment by mattmcneeney** [comment]
Thanks all! 😄

**Pull request merged**
