### PR TITLE
Add support for ETag and If-Modified-Since headers

### LINKED ISSUE #209: Expand spec to allow for "no changes" semantics to be returned by brokers
Currently when a catalog is fetched from the broker, the broker returns the entire catalog. There might be cases where generating the catalog is expensive, or the catalog returned is quite large. Some controllers might also refetch the catalog on regular basis (like kubernetes service catalog), and having a way for the controller to specify what the latest version (or the time it last fetched it) and having a broker respond with no changes would make it easier for controller writers to just check the response without doing diffs on existing vs. new catalog.
Seems like with the if-match and if-not-modified-since or if-not-modified-since as optionally being allowed to be returned by a broker would achieve this.

### PR DESCRIPTION
**Pull request by fmui**
**What is the problem this PR solves?**
Closes #209: "Expand spec to allow for "no changes" semantics to be returned by brokers"

edit: changed to closes so the issue gets closed automatically

### CODE REVIEW

**Comment by mattmcneeney** [comment]
@jberkhahn This sounds like it might be useful for svc-cat. Do you think you'd add this to the backlog of things?

**Comment by jberkhahn** [comment]
this sounds useful for us, yes

**Comment by mattmcneeney** [comment]
I think this looks good, though I'm not sure when the CF folks would be able to get around to adding support for this. But it's more useful for svc-cat anyway since CF doesn't periodically poll catalog endpoints today.

**Comment by fmui** [comment]
Review please @jberkhahn @tinygrasshopper

**Pull request merged**
