### PR TITLE
Remove unsupported OpenAPI spec reference to JSON Schema

### LINKED ISSUE #734: OpenAPI spec points to unsupported JSON schema definition
**What is the problem?**

The openapi definition points to the JSON schema URL as a `$ref` and this breaks client generation since the OpenAPI spec doesn't implement all the keywords present in this schema definition. 

**Who does this affect?**

When we try to generate clients out of the openapi.yaml file we have to skip validation and usually edit the generated files to remove or fix the objects generated, in some cases the generation fails altogether because of a single field.

The swagger.yaml file defines the same field as an object and doesn't suffer from the same issue.

**Do you have any proposed solutions?**
Change the field to an `object` like we do in the swagger file

**Additional context**

https://github.com/openservicebrokerapi/servicebroker/blob/master/openapi.yaml#L743

```
openapi-generator generate -g protobuf-schema -i openapi.yaml -o protobuf
[main] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while reading:
java.lang.RuntimeException: Could not find components/schemas/# in contents of http://json-schema.org/draft-04/schema
	at io.swagger.v3.parser.ResolverCache.loadRef(ResolverCache.java:145)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema(ExternalRefProcessor.java:60)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefSchema(ExternalRefProcessor.java:897)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processSchema(ExternalRefProcessor.java:201)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processProperties(ExternalRefProcessor.java:224)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processSchema(ExternalRefProcessor.java:215)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processProperties(ExternalRefProcessor.java:224)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processProperties(ExternalRefProcessor.java:231)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema(ExternalRefProcessor.java:158)
	at io.swagger.v3.parser.processors.SchemaProcessor.processReferenceSchema(SchemaProcessor.java:214)
	at io.swagger.v3.parser.processors.SchemaProcessor.processSchema(SchemaProcessor.java:37)
	at io.swagger.v3.parser.processors.ComponentsProcessor.processSchemas(ComponentsProcessor.java:226)
	at io.swagger.v3.parser.processors.ComponentsProcessor.processComponents(ComponentsProcessor.java:140)
	at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:50)
	at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:67)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:461)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:507)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:423)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

### PR DESCRIPTION
**Pull request by rsampaio**
**What is the problem this PR solves?**

Remove the JSON Schema reference from the field and turn it into an object like the swagger file.
Adds required tags and an `_` to one of the states since spaces are not supported by OpenAPI when the field is an enum so the spec passes validation from tools like gnostic or openapi-generator.

**Checklist:**
- [x] The [swagger.yaml](swagger.yaml) doc has been updated with any required changes
- [x] The [openapi.yaml](openapi.yaml) doc has been updated with any required changes

Fixes #734 

After applying this changes openapi can generate bindings for any language without any issue:

```
openapi-generator generate -g protobuf-schema -i openapi.yaml -o protobuf
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] WARN  o.o.c.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: protobuf-schema (config)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'protobuf-schema' is considered beta.
[main] INFO  o.o.codegen.DefaultGenerator - Model Context not generated since it's a free-form object
[main] INFO  o.o.codegen.DefaultGenerator - Model Metadata not generated since it's a free-form object
[main] INFO  o.o.codegen.DefaultGenerator - Model Object not generated since it's a free-form object
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/async_operation.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/catalog.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/dashboard_client.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/error.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/last_operation_resource.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/maintenance_info.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/plan.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/schemas.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_binding_endpoint.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_binding_metadata.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_binding_request.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_binding_resouce_object.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_binding_resource.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_binding_response.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_binding_schema.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_binding_volume_mount.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_binding_volume_mount_device.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_instance_async_operation.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_instance_metadata.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_instance_previous_values.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_instance_provision_request_body.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_instance_provision_response.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_instance_resource.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_instance_schema.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_instance_schema_create.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/models/service_instance_update_request_body.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/services/catalog_service.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/services/service_bindings_service.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/services/service_instances_service.proto
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/README.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/.openapi-generator-ignore
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/rvaz/Code/servicebroker/protobuf/.openapi-generator/VERSION
```

### CODE REVIEW

**Comment by Samze** [comment]
As per the conversation on the bi-weekly call today, the `in_progress` change here might be problematic as the spec includes the space, so `in progress` is accurate as the enum field. The rest LGTM.

**Comment by rsampaio** [comment]
@Samze after reading the OpenAPI specification I figured we could change the value of the enum to a string and that would be enough to satisfy the generator, I pushed the change to this branch and now the values are the same as before and correctly interpreted by the generator. I'm looking into the CLA issue today.

**Comment by rsampaio** [comment]
@Samze I believe the CLA is authorized but I can't load the EasyCLA page to confirm that, are you able to verify and maybe re-run the validation?

**Review by Samze — APPROVED** [review]
LGTM!

**Review by gberche-orange — APPROVED** [review]
LGTM, however I'm not an approver on the project

**Review by avilupu — APPROVED** [review]

**Review by tinygrasshopper — APPROVED** [review]

**Pull request merged**
