### PR TITLE
Better getting started guide

### PR DESCRIPTION
**Pull request by mattmcneeney**
Let me know what you all think of this. I thought we could do a slightly better job at helping new Service Broker authors get up and running and understand what resources are out there for them to use.

### CODE REVIEW

**Comment by mattmcneeney** [comment]
cc @arschles as this may affect #394

**Comment by angarg12** [comment]
LGTM this is a great idea, some sort of high level introduction to the project is very welcome :smiley:

**Comment by avade** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
rebase needed

**Comment by mattmcneeney** [comment]
Rebased!

**Comment by duglin** [comment]
thanks
LGTM

**Comment by avade** [comment]
doh - LGTM

**Comment by angarg12** [comment]
LGTM

**Comment by fmui** [comment]
LGTM

**Pull request merged**
