### PR TITLE
Adding a sample service broker for Azure support

### PR DESCRIPTION
**Pull request by arschles**
This patch adds the [Open Service Broker for Azure](https://github.com/Azure/open-service-broker-azure) to the list of sample brokers. This is per the suggestion at https://docs.google.com/document/d/1OqY5DoJuRKnlyF1w1XrhxlW9PjymEStU3IIG0qQLXfg/edit?disco=AAAABb4e6os

### CODE REVIEW

**Comment by avade** [comment]
LGTM

We should refactor this page to split out samples from actual products.

**Comment by mattmcneeney** [comment]
Woohoo! LGTM

**Comment by angarg12** [comment]
LGTM

Would it make sense to move samples to the Wiki so we don't need PRs to introduce new links?

**Comment by duglin** [comment]
LGTM

**Pull request merged**
