### PR TITLE
add colon(:)

### LINKED ISSUE #569: json in spec.md miss colon(:)
```
{
  "services": [{
    "name": "fake-service",
    "id": "acb56d7c-XXXX-XXXX-XXXX-feb140a59a66",
    "description": "A fake service.",
    "tags": ["no-sql", "relational"],
    "requires": ["route_forwarding"],
    "bindable": true,
    "instances_retrievable": true,
    "bindings_retrievable" true,
    ...
}
```
should be 

**"bindings_retrievable": true,**

### PR DESCRIPTION
**Pull request by yancai**
fix #569

### CODE REVIEW

**Comment by duglin** [comment]
LGTM once CLA is done

**Comment by mattmcneeney** [comment]
@yancai Please could you sign the CLA and then let us know? I can then close and reopen this PR. PMC members should hold off approving this for now as we will have to do it again.

**Comment by duglin** [comment]
@yancai can you please sign the CLA? If not someone else can do this fix for you - just let us know

**Comment by yancai** [comment]
@duglin Sorry, I am currently on a business trip until July 23. I can't sign the CLA now. If you want to fix this urgently, you can find someone else to fix this bug.

**Comment by duglin** [comment]
No, I don't think its urgent, we can wait - thanks for the update

**Comment by yancai** [comment]
@duglin I have signed CLA and sent to contributors@cloudfoundry.org

**Comment by duglin** [comment]
@yancai thanks!

**Comment by duglin** [comment]
really easy review!  3 more needed

**Comment by mattmcneeney** [comment]
CLA signing success!

**Pull request merged**
