### PR TITLE
accepts_incomplete is a param, not a request body field

### PR DESCRIPTION
**Pull request by shalako**

### CODE REVIEW

**Comment by duglin** [comment]
does this mean that the CF docs are wrong too?

**Comment by duglin** [comment]
Or was just this a mistake made during the translation?

**Comment by shalako** [comment]
Looking back at the history of the cloudfoundry/docs-services repo, it
appears this has been an error in the docs since support for async
operations was introduced.  I would have signed off on the docs change and
so must have missed the error. I just double-checked that Cloud Controller
sends accepts_incomplete to brokers as a param, not a body field.



Shannon Coen
Product Manager, Cloud Foundry
Pivotal, Inc.

**Comment by duglin** [comment]
ok then.  LGTM

**Comment by duglin** [comment]
LGTM

**Comment by angarg12** [comment]
LGTM

**Comment by avade** [comment]
lgtm

**Comment by pmorie** [comment]
LGTM, but needs rebase @shalako

**Comment by duglin** [comment]
Looks like we need to re-LGTM due to the rebase/push.

LGTM

**Comment by angarg12** [comment]
Good catch, lets try to get this out the door.

LGTM

**Comment by avade** [comment]
LGTM

**Comment by avade** [comment]
@pmorie or @petereberlein can you take a look so we can get this merged.

**Comment by petereberlein** [comment]
LGTM

**Pull request merged**
